### ISSUE TITLE
How to get result base64 string?

### ISSUE THREAD

**Issue by mflash123** [onurzorluer/react-image-file-resizer#16]
I find example of this
```
let filesToStore = []
  Resizer.imageFileResizer(
                  file,
                  331,
                  700,
                  'JPEG',
                  100,
                  0,
                  blob => {
                    filesToStore.push(blob)
                  },
                  'base64'
              )
```
And if I make console.log(filesToStore) it works.
But I thinks there a some promise or what, because I cant get result when page loaded. Only after few seconds.

So, how can I get result string?
Example:
```
let filesToStore = 'string'
  Resizer.imageFileResizer(
                  file,
                  331,
                  700,
                  'JPEG',
                  100,
                  0,
                  blob => {
                    filesToStore = blob
                  },
                  'base64'
              )
console.log(filesToStore)
```
 **filesToStore returns 'string', not blob result.**

**Comment by onurzorluer** [comment]
You must change last parameter to blob.
`let filesToStore = 'string'
  Resizer.imageFileResizer(
                  file,
                  331,
                  700,
                  'JPEG',
                  100,
                  0,
                  blob => {
                    filesToStore = blob
                  },
                  '**blob**'
              )
console.log(filesToStore)`

**Comment by rikinshah23** [comment]
I have tried this but its shows me blank result. What am I doing wrong?


    var imageURI = '';
    const resizedImg = await Resizer.imageFileResizer(
      fileList.fileList[0].originFileObj,
      300,
      300,
      'JPEG',
      100,
      0,
      uri  => {
        imageURI = uri 
        console.log(uri )
      },
      'blob'
    );
    console.log(resizedImg)
    console.log(imageURI)
