### ISSUE TITLE
Typescript implementation??

### ISSUE THREAD

**Issue by apoorvmote** [onurzorluer/react-image-file-resizer#22]
**Is your feature request related to a problem? Please describe.**
I want to use it with typescript react.

**Describe the solution you'd like**
type definition @types/react-image-file-resizer

**Describe alternatives you've considered**
I just want to create 150 x 150 thumbnail. I will have to do that on server.

**Comment by Sandun-Isuru-Niraj** [comment]
I have used this code for my ReactTS project by adapting it to the Typescript. If you Okay I can contribute it to this repo.

**Comment by onurzorluer** [comment]
@Sandun-Isuru-Niraj it's great idea. Contributions of any kind welcome!
