### ISSUE TITLE
`/build` directory is not updated on NPM (v0.1.6)

### ISSUE THREAD

**Issue by AhmadMaleki** [onurzorluer/react-image-file-resizer#3]
**Describe the bug**
Version is updated from `0.1.5` to `0.1.6` and the `/src` directory is updated on npm to include [This PR](https://github.com/onurzorluer/react-image-file-resizer/pull/1). But I think the project is not built on npm because the `/build` directory is not updated.

**To Reproduce**
1. `npm i -S react-image-file-resizer`
2. Compare the `/src/index.js` and `/build/index.js` files.

**Expected behavior**
`/build` directory should include the latest update which involves the exported function to have 8 arguments.

**Screenshots**
This is the part in `/src/index.js`: (_Note 8 arguments_) 
![src](https://user-images.githubusercontent.com/26637638/54287707-6eb3f880-45bb-11e9-9a53-89eba15eacb3.PNG)
This is the corresponding part in `/build/index.js`: (_Note 7 arguments_) 
![build](https://user-images.githubusercontent.com/26637638/54287794-96a35c00-45bb-11e9-9add-34b09ab10147.PNG)

**Desktop:**
 - OS: Windows
 - Version 0.1.6

**Comment by onurzorluer** [comment]
Thanks, this issue solved with v0.1.7.
