### ISSUE TITLE
how do we use the file that it returns??

### ISSUE THREAD

**Issue by Utsav170** [onurzorluer/react-image-file-resizer#4]
how to use the file after it is resized. how can we use the uri in using the image name??

**Comment by sharmad247** [comment]
Use it this way, snippet from one of my projects.

The files are stored in state as filesToStore

`   let filesToStore = []

    if (event.target.files)
    {
      files.forEach(file=>{
        Resizer.imageFileResizer(
          file,
          500,
          500,
          'PNG',
          100,
          0,
          blob => {
            filesToStore.push(blob)
          },
          'blob'
        );
      })
      this.setState({
        filesToStore: filesToStore
      });
    }`
