### ISSUE TITLE
PNG or WEBP images with transparancy turn black upon conversion to jpeg

### ISSUE THREAD

**Issue by zehawki** [onurzorluer/react-image-file-resizer#40]
**Describe the bug**
Any png or webp image which has a transparency layer, turns to black back when converted to jpeg

**To Reproduce**
1. Take any png image eg http://www.pngmart.com/image/153441
2. compressFormat = 'JPEG'

**Expected behavior**
Transparent back should preferably turn white. This is what photoshop does BTW.

**Comment by DickShern** [comment]
Is there any updates to this? I would prefer to export with a white background as well

**Comment by andresriveratoro** [comment]
See https://github.com/onurzorluer/react-image-file-resizer/pull/54

**Comment by jpnuma** [comment]
Still waiting for author to merge this PR

**Comment by khanakia** [comment]
Any update below image turns to black on resize

![switch (1)](https://github.com/onurzorluer/react-image-file-resizer/assets/2174170/f13f03cf-68e4-4a0f-83e6-ac70c3085912)
