### ISSUE TITLE
How can I get an error response from Resizer.imageFileResizer when resizing fails (fake images,etc.).

### ISSUE THREAD

**Issue by nfabacus** [onurzorluer/react-image-file-resizer#41]
**Is your feature request related to a problem? Please describe.**
  Yes, how do I know when resizer fails to resize.

**Describe the solution you'd like**
   Get an error message/response from Resizer so that I can handle it.

**Describe alternatives you've considered**
  I tried to get response rom Resizer but it does not return anything when resizing fails.

**Comment by onurzorluer** [comment]
Error handling has been applied, now you can catch errors. The examples in the readme file have been updated.
