### ISSUE TITLE
I cant resize image to the exact target size

### ISSUE THREAD

**Issue by monire91** [onurzorluer/react-image-file-resizer#43]
**Is your feature request related to a problem? Please describe.**
Im not sure
**Describe the solution you'd like**
a snippet on how to get target size say 1136x574

**Describe alternatives you've considered**

**Additional context**

**Comment by onurzorluer** [comment]
You should set minimum and maximum values as 1136x574.

`Resizer.imageFileResizer(
                event.target.files[0],
                1136,
                574,
                'JPEG',
                100,
                0,
                uri => {
                    console.log(uri)
                    this.setState({ newImage: uri })
                },
                'base64',
                1136,
                574,
                );`

**Comment by gabgagnon** [comment]
@onurzorluer, it's not working for me, did I miss something?

````
    const file = e.target.files[0];
    return new Promise((resolve) => {
      Resizer.imageFileResizer(file, 300, 250, "JPEG", quality, 0, (uri) => { resolve(uri); }, "blob", 300, 250);
    });
````

**Comment by onurzorluer** [comment]
@gabgagnon `Resizer.imageFileResizer(file, 300, 250, "JPEG", **quality,** 0, (uri) => { resolve(uri); }, "blob", 300, 250);`

You must give numerical value to the quality parameter.
