### ISSUE TITLE
PNG transparency is lost even when using compressFormat PNG

### ISSUE THREAD

**Issue by peterzanetti** [onurzorluer/react-image-file-resizer#56]
I'm pretty baffled that this is the case, but indeed it seems to be.

My function looks like

`  resizeFaviconLogo = (file) =>
    new Promise((resolve) => {
      Resizer.imageFileResizer(
        file,
        256,
        256,
        'PNG',
        100,
        0,
        (uri) => {
          resolve(uri);
        },
        'file'
      );
    });`

And the output PNG has a white background instead of transparency.

**Comment by peterzanetti** [comment]
Please tell me this is not intended behavior and I didn't waste an entire day integrating this library only to find that it destroys every PNG it touches.

**Comment by onurzorluer** [comment]
fixed in v0.4.7

**Comment by peterzanetti** [comment]
You're a hero. Thank you very much.
